//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.18 at 01:10:44 PM CEST 
//


package com.epam.tamasknizner.springadvancedtraining.soap.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userAccount"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}domainObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="prepaidAmount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userAccount", propOrder = {
    "prepaidAmount"
})
public class UserAccount
    extends DomainObject
{

    protected double prepaidAmount;

    /**
     * Gets the value of the prepaidAmount property.
     * 
     */
    public double getPrepaidAmount() {
        return prepaidAmount;
    }

    /**
     * Sets the value of the prepaidAmount property.
     * 
     */
    public void setPrepaidAmount(double value) {
        this.prepaidAmount = value;
    }

}
